INSERT INTO territory_quarters
(id, name, code, created_at, updated_at)
VALUES
(1, 'Akebe', 'AK', NOW(), NOW()),
(2, 'Alibandeng', 'AL', NOW(), NOW()),
(3, 'Ancien Sobraga', 'AS', NOW(), NOW()),
(4, 'Atong Abe', 'AA', NOW(), NOW()),
(5, 'Atsibing Toss', 'AT', NOW(), NOW()),
(6, 'Avea', 'AV', NOW(), NOW()),
(7, 'Bambou Chine', 'BC', NOW(), NOW()),
(8, 'Bessieux', 'BS', NOW(), NOW()),
(9, 'Boulevard', 'BL', NOW(), NOW()),
(10, 'Campagne', 'CA', NOW(), NOW()),
(11, 'Charbonnage', 'CH', NOW(), NOW()),
(12, 'Cite De La Caisse', 'CC', NOW(), NOW()),
(13, 'Cite Mebiame', 'CM', NOW(), NOW()),
(14, 'Cocotiers', 'CO', NOW(), NOW()),
(15, 'Derriere La Prison', 'DP', NOW(), NOW()),
(16, 'Derriere Ecole Normale', 'EN', NOW(), NOW()),
(17, "Derriere l'Hopital", 'DH', NOW(), NOW()),
(18, 'Dragon', 'DG', NOW(), NOW()),
(19, 'Fromager', 'FR', NOW(), NOW()),
(20, 'Gare-routiere', 'GR', NOW(), NOW()),
(21, 'Likoula', 'LK', NOW(), NOW()),
(22, 'London', 'LN', NOW(), NOW()),
(23, 'Louis', 'LO', NOW(), NOW()),
(24, 'Mont-bouet', 'MB', NOW(), NOW()),
(25, 'Nkembo', 'NK', NOW(), NOW()),
(26, 'Nzeng Ayong', 'NZ', NOW(), NOW()),
(27, 'Okala', 'OK', NOW(), NOW()),
(28, 'Pavillon', 'PV', NOW(), NOW()),
(29, 'Peyrie', 'PY', NOW(), NOW()),
(30, 'PK', 'PK', NOW(), NOW()),
(31, 'Plaine Orety', 'PO', NOW(), NOW()),
(32, 'Rio', 'RIO', NOW(), NOW()),
(33, 'Sainte Anne', 'SA', NOW(), NOW()),
(34, 'Sorbonne', 'SR', NOW(), NOW()),
(35, 'Sotega', 'ST', NOW(), NOW()),
(36, 'Venez Voir', 'VV', NOW(), NOW());