INSERT INTO territories
(id, name, code, number, quarter, created_at, updated_at)
VALUES
(1, 'Akebe 1', 'AK1', 1, 'Akebe', NOW(), NOW()),
(2, 'Akebe 2', 'AK2', 2, 'Akebe', NOW(), NOW()),
(3, 'Akebe 3', 'AK3', 3, 'Akebe', NOW(), NOW()),
(4, 'Akebe 4', 'AK4', 4, 'Akebe', NOW(), NOW()),
(5, 'Akebe 5', 'AK5', 5, 'Akebe', NOW(), NOW()),
(6, 'Akebe 6', 'AK6', 6, 'Akebe', NOW(), NOW()),
(7, 'Akebe 7', 'AK7', 7, 'Akebe', NOW(), NOW()),
(8, 'Alibandeng 1', 'AL1', 1, 'Alibandeng', NOW(), NOW()),
(9, 'Alibandeng 2', 'AL2', 2, 'Alibandeng', NOW(), NOW()),
(10, 'Alibandeng 3', 'AL3', 3, 'Alibandeng', NOW(), NOW()),
(11, 'Ancien Sobraga 1', 'AS1', 1, 'Ancien Sobraga', NOW(), NOW()),
(12, 'Ancien Sobraga 2', 'AS2', 2, 'Ancien Sobraga', NOW(), NOW()),
(13, 'Ancien Sobraga 3', 'AS3', 3, 'Ancien Sobraga', NOW(), NOW()),
(14, 'Ancien Sobraga 4', 'AS4', 4, 'Ancien Sobraga', NOW(), NOW()),
(15, 'Atong Abe 1', 'AA1', 1, 'Atong Abe', NOW(), NOW()),
(16, 'Atong Abe 2', 'AA2', 2, 'Atong Abe', NOW(), NOW()),
(17, 'Atong Abe 3', 'AA3', 3, 'Atong Abe', NOW(), NOW()),
(18, 'Atong Abe 4', 'AA4', 4, 'Atong Abe', NOW(), NOW()),
(19, 'Atsibing Toss 1', 'AT1', 1, 'Atsibing Toss', NOW(), NOW()),
(20, 'Atsibing Toss 2', 'AT2', 2, 'Atsibing Toss', NOW(), NOW()),
(21, 'Avea 1', 'AV1', 1, 'Avea', NOW(), NOW()),
(22, 'Avea 2', 'AV2', 2, 'Avea', NOW(), NOW()),
(23, 'Avea 3', 'AV3', 3, 'Avea', NOW(), NOW()),
(24, 'Bessieux 1', 'BS1', 1, 'Bessieux', NOW(), NOW()),
(25, 'Boulevard 1', 'BL1', 1, 'Boulevard', NOW(), NOW()),
(26, 'Campagne 1', 'CA1', 1, 'Campagne', NOW(), NOW()),
(27, 'Campagne 2', 'CA2', 2, 'Campagne', NOW(), NOW()),
(28, 'Campagne 3', 'CA3', 3, 'Campagne', NOW(), NOW()),
(29, 'Charbonage 1', 'CH1', 1, 'Charbonage', NOW(), NOW()),
(30, 'Charbonage 2', 'CH2', 2, 'Charbonage', NOW(), NOW()),
(31, 'Charbonage 3', 'CH3', 3, 'Charbonage', NOW(), NOW()),
(32, 'Charbonage 4', 'CH4', 4, 'Charbonage', NOW(), NOW()),
(33, 'Cite De La Caisse 1', 'CC1', 1, 'Cite De La Caisse', NOW(), NOW()),
(34, 'Cite De La Caisse 2', 'CC2', 2, 'Cite De La Caisse', NOW(), NOW()),
(35, 'Cite Mebiame', 'CM1', 1, 'Cite Mebiame', NOW(), NOW()),
(36, 'Cocotiers 1', 'CO1', 1, 'Cocotiers', NOW(), NOW()),
(37, 'Cocotiers 2', 'CO2', 2, 'Cocotiers', NOW(), NOW()),
(38, 'Cocotiers 3', 'CO3', 3, 'Cocotiers', NOW(), NOW()),
(39, 'Cocotiers 4', 'CO4', 4, 'Cocotiers', NOW(), NOW()),
(40, 'Cocotiers 5', 'CO5', 5, 'Cocotiers', NOW(), NOW()),
(41, 'Cocotiers 6', 'CO6', 6, 'Cocotiers', NOW(), NOW()),
(42, 'Derriere La Prison 1', 'DP1', 1, 'Derriere La Prison', NOW(), NOW()),
(43, 'Derriere La Prison 2', 'DP2', 2, 'Derriere La Prison', NOW(), NOW()),
(44, 'Derriere La Prison 3', 'DP3', 3, 'Derriere La Prison', NOW(), NOW()),
(45, 'Derriere La Prison 4', 'DP4', 4, 'Derriere La Prison', NOW(), NOW()),
(46, 'Derriere Hopital 1', 'DH1', 1, 'Derriere Hopital', NOW(), NOW()),
(47, 'Derriere Hopital 2', 'DH2', 2, 'Derriere Hopital', NOW(), NOW()),
(48, 'Dragon 1', 'DG1', 1, 'Dragon', NOW(), NOW()),
(49, 'Fromager 1', 'FM1', 1, 'Fromager', NOW(), NOW()),
(50, 'Fromager 2', 'FM2', 2, 'Fromager', NOW(), NOW()),
(51, 'Gare-routiere 1', 'GR1', 1, 'Gare-routiere', NOW(), NOW()),
(52, 'Gare-routiere 2', 'GR2', 2, 'Gare-routiere', NOW(), NOW()),
(53, 'Likouala 1', 'LK1', 1, 'Likouala', NOW(), NOW()),
(54, 'Likouala 2', 'LK2', 2, 'Likouala', NOW(), NOW()),
(55, 'London 1', 'LN1', 1, 'London', NOW(), NOW()),
(56, 'Louis 1', 'LO1', 1, 'Louis', NOW(), NOW()),
(57, 'Louis 2', 'LO2', 2, 'Louis', NOW(), NOW()),
(58, 'Louis 3', 'LO3', 3, 'Louis', NOW(), NOW()),
(59, 'Louis 4', 'LO4', 4, 'Louis', NOW(), NOW()),
(60, 'Mont-bouet 1', 'MB1', 1, 'Mont-bouet', NOW(), NOW()),
(61, 'Nkembo 1', 'NK1', 1, 'Nkembo', NOW(), NOW()),
(62, 'Nzeng Ayong 1', 'NZ1', 1, 'Nzeng Ayong', NOW(), NOW()),
(63, 'Nzeng Ayong 2', 'NZ2', 2, 'Nzeng Ayong', NOW(), NOW()),
(64, 'Nzeng Ayong 3', 'NZ3', 3, 'Nzeng Ayong', NOW(), NOW()),
(65, 'Nzeng Ayong 4', 'NZ4', 4, 'Nzeng Ayong', NOW(), NOW()),
(66, 'Nzeng Ayong 5', 'NZ5', 5, 'Nzeng Ayong', NOW(), NOW()),
(67, 'Nzeng Ayong 6', 'NZ6', 6, 'Nzeng Ayong', NOW(), NOW()),
(68, 'Nzeng Ayong 7', 'NZ7', 7, 'Nzeng Ayong', NOW(), NOW()),
(69, 'Nzeng Ayong 8', 'NZ8', 8, 'Nzeng Ayong', NOW(), NOW()),
(70, 'Nzeng Ayong 9', 'NZ9', 9, 'Nzeng Ayong', NOW(), NOW()),
(71, 'Nzeng Ayong 10', 'NZ10', 10, 'Nzeng Ayong', NOW(), NOW()),
(72, 'Nzeng Ayong 11', 'NZ11', 11, 'Nzeng Ayong', NOW(), NOW()),
(73, 'Nzeng Ayong 12', 'NZ12', 12, 'Nzeng Ayong', NOW(), NOW()),
(74, 'Nzeng Ayong 13', 'NZ13', 13, 'Nzeng Ayong', NOW(), NOW()),
(75, 'Nzeng Ayong 14', 'NZ14', 14, 'Nzeng Ayong', NOW(), NOW()),
(76, 'Nzeng Ayong 15', 'NZ15', 15, 'Nzeng Ayong', NOW(), NOW()),
(77, 'Nzeng Ayong 16', 'NZ16', 16, 'Nzeng Ayong', NOW(), NOW()),
(78, 'Okala 1', 'OK1', 1, 'Okala', NOW(), NOW()),
(79, 'Okala 2', 'OK2', 2, 'Okala', NOW(), NOW()),
(80, 'Okala 3', 'OK3', 3, 'Okala', NOW(), NOW()),
(81, 'Okala 4', 'OK4', 4, 'Okala', NOW(), NOW()),
(82, 'Pavillon 1', 'PV1', 1, 'Pavillon', NOW(), NOW()),
(83, 'Peyrie 1', 'PY1', 1, 'Peyrie', NOW(), NOW()),
(84, 'Peyrie 2', 'PY2', 2, 'Peyrie', NOW(), NOW()),
(85, 'Peyrie 3', 'PY3', 3, 'Peyrie', NOW(), NOW()),
(86, 'PK 6', 'PK6', 6, 'PK', NOW(), NOW()),
(87, 'PK 7', 'PK7', 7, 'PK', NOW(), NOW()),
(88, 'PK 8', 'PK8', 8, 'PK', NOW(), NOW()),
(89, 'PK 9', 'PK9', 9, 'PK', NOW(), NOW()),
(90, 'PK 10', 'PK10', 10, 'PK', NOW(), NOW()),
(91, 'PK 11', 'PK11', 11, 'PK', NOW(), NOW()),
(92, 'PK 12', 'PK12', 12, 'PK', NOW(), NOW()),
(93, 'Plaine Orety 1', 'PO1', 1, 'Plaine Orety', NOW(), NOW()),
(94, 'Plaine Orety 2', 'PO2', 2, 'Plaine Orety', NOW(), NOW()),
(95, 'Rio 1', 'RIO1', 1, 'Rio', NOW(), NOW()),
(96, 'Rio 2', 'RIO2', 2, 'Rio', NOW(), NOW()),
(97, 'Sainte Anne 1', 'SA1', 1, 'Sainte Anne', NOW(), NOW()),
(98, 'Sorbonne 1', 'SR1', 1, 'Sorbonne', NOW(), NOW()),
(99, 'Sotega 1', 'SO1', 1, 'Sotega', NOW(), NOW()),
(100, 'Sotega 2', 'SO2', 2, 'Sotega', NOW(), NOW()),
(101, 'Sotega 3', 'SO3', 3, 'Sotega', NOW(), NOW()),
(102, 'Sotega 4', 'SO4', 4, 'Sotega', NOW(), NOW()),
(103, 'Sotega 5', 'SO5', 5, 'Sotega', NOW(), NOW()),
(104, 'Sotega 6', 'SO6', 6, 'Sotega', NOW(), NOW()),
(105, 'Sotega 7', 'SO7', 7, 'Sotega', NOW(), NOW()),
(106, 'Venez Voir 1', 'VV1', 1, 'Venez Voir', NOW(), NOW());